version: '3.8'

services:
  ems-backend:
    build: .
    container_name: ems-backend-production
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data:z
    restart: always